project_name: focus

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
      - goos: linux
        goarch: arm64
    main: ./cmd/focus

archives:
  - files:
      - LICENCE
      - README.md
      - CHANGELOG.md
    format_overrides:
      - goos: windows
        format: zip

snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  - id: main_packages
    vendor: Freshman
    homepage: https://freshman.tech
    maintainer: Ayooluwa Isaiah <ayo@freshman.tech>
    description:
      Focus is a command-line productivity timer based on the Pomodoro Technique
    license: MIT
    formats:
      - deb
      - rpm

    overrides:
      deb:
        dependencies:
          - libasound2-dev

      rpm:
        dependencies:
          - alsa-lib-devel

  - id: other_packages
    vendor: Freshman
    homepage: https://freshman.tech
    maintainer: Ayooluwa Isaiah <ayo@freshman.tech>
    description:
      Focus is a command-line productivity timer based on the Pomodoro Technique
    license: MIT
    formats:
      - apk
      - termux.deb
      - archlinux

    dependencies:
      - libasound2-dev

    overrides:
      archlinux:
        dependencies:
          - alsa-lib

publishers:
  - name: fury.io
    ids:
      - main_packages
    dir: '{{ dir .ArtifactPath }}'
    cmd:
      curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_PUSH_TOKEN
      }}@push.fury.io/{{ .Env.FURY_USERNAME }}/

#TODO: Support chocolatey
#TODO: Support Winget

scoops:
  - url_template:
      'https://github.com/ayoisaiah/focus/releases/download/{{ .Tag }}/{{
      .ArtifactName }}'
    repository:
      owner: ayoisaiah
      name: scoop-bucket
      token: '{{ .Env.SCOOP_BUCKET_GITHUB_TOKEN }}'
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    commit_msg_template: 'Scoop update for {{ .ProjectName }} {{ .Tag }}'
    homepage: 'https://github.com/ayoisaiah/focus'
    description:
      'Focus is a command-line productivity timer based on the Pomodoro
      Technique'
    license: MIT

brews:
  - install: |-
      bin.install "focus"

    homepage: 'https://github.com/ayoisaiah/focus'

    license: 'MIT'
