project_name: focus

before:
  hooks:
    - go mod download

builds:
  - id: windows
    env:
      - CGO_ENABLED=1
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    main: ./cmd/focus

  - id: linux
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/focus

archives:
  - id: windows-only
    builds:
      - windows
    files:
      - LICENCE
      - README.md
      - CHANGELOG.md
    format: zip

  - id: default
    builds:
      - windows
      - linux
    files:
      - LICENCE
      - README.md
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: 'master'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  - id: main_packages
    vendor: '{{ .Env.REPO_OWNER }}'
    homepage: '{{ .Env.REPO_WEBSITE }}'
    maintainer: '{{ .Env.REPO_MAINTAINER }}'
    description: '{{ .Env.REPO_DESCRIPTION }}'
    license: MIT
    formats:
      - deb
      - rpm

    overrides:
      deb:
        dependencies:
          - libasound2-dev

      rpm:
        dependencies:
          - alsa-lib-devel

  - id: other_packages
    vendor: '{{ .Env.REPO_OWNER }}'
    homepage: '{{ .Env.REPO_WEBSITE }}'
    maintainer: '{{ .Env.REPO_MAINTAINER }}'
    description: '{{ .Env.REPO_DESCRIPTION }}'
    license: MIT
    formats:
      - apk
      - termux.deb
      - archlinux

    dependencies:
      - libasound2-dev

    overrides:
      archlinux:
        dependencies:
          - alsa-lib

publishers:
  - name: fury.io
    ids:
      - main_packages
    dir: '{{ dir .ArtifactPath }}'
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_PUSH_TOKEN }}@push.fury.io/{{ .Env.FURY_USERNAME }}/

winget:
  - publisher: '{{ .Env.REPO_OWNER }}'
    license: MIT
    copyright: '{{ .Env.REPO_AUTHOR_NAME }}'
    homepage: '{{ .Env.REPO_WEBSITE }}'
    short_description: '{{ .Env.REPO_DESCRIPTION }}'
    repository:
      owner: '{{ .Env.REPO_OWNER }}'
      token: '{{ .Env.GORELEASER_GITHUB_TOKEN }}'
      name: winget-pkgs
      branch: '{{.ProjectName}}-{{.Version}}'
      pull_request:
        enabled: true
        draft: false
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master

scoops:
  - ids:
      - windows-only
    url_template: 'https://github.com/ayoisaiah/focus/releases/download/{{ .Tag }}/{{ .ArtifactName }}'
    repository:
      owner: '{{ .Env.REPO_OWNER }}'
      name: scoop-bucket
      token: '{{ .Env.GORELEASER_GITHUB_TOKEN }}'
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    homepage: '{{ .Env.REPO_WEBSITE }}'
    description: '{{ .Env.REPO_DESCRIPTION }}'
    license: MIT

brews:
  - repository:
      owner: '{{ .Env.REPO_OWNER }}'
      name: homebrew-tap
      token: '{{ .Env.GORELEASER_GITHUB_TOKEN }}'
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    homepage: '{{ .Env.REPO_WEBSITE }}'
    description: '{{ .Env.REPO_DESCRIPTION }}'
    install: |-
      bin.install "{{ with .Env.REPO_BINARY_NAME }}{{ . }}{{ else }}{{ .ProjectName }}{{ end }}"
