before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
      - goos: linux
        goarch: arm64
    main: ./cmd/focus
archives:
  -
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: amd64
      arm64: arm64

    files:
      - LICENCE
      - README.md
      - CHANGELOG.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  -
    id: focus
    package_name: focus
    file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    vendor: Freshman
    homepage: https://freshman.tech
    maintainer: Ayooluwa Isaiah <ayo@freshman.tech>
    description: Focus is a command-line productivity timer based on the Pomodoro Technique
    license: MIT
    formats:
      - deb
      - rpm
scoop:
  url_template: 'https://github.com/ayoisaiah/focus/releases/download/{{ .Tag }}/{{ .ArtifactName }}'
  bucket:
    owner: ayoisaiah
    name: scoop-bucket
    token: '{{ .Env.SCOOP_BUCKET_GITHUB_TOKEN }}'
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
  commit_msg_template: 'Scoop update for {{ .ProjectName }} version {{ .Tag }}'
  homepage: 'https://github.com/ayoisaiah/focus'
  description: 'Focus is a command-line productivity timer based on the Pomodoro Technique'
  license: MIT
