repos:
-   repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-beta.4
    hooks:
    -   id: my-cmd
        name: golines
        args: [golines, '-m', '80', '-w', '--']
        always_run: false
        verbose: false
    -   id: go-build-repo-mod
    -   id: go-test-repo-mod
    -   id: go-imports
    -   id: golangci-lint-repo-mod
