name: File a bug report
description: Report an issue with Focus
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a bug report for Focus. To assist us in replicating and resolving your issue, kindly fill the following fields as per their descriptions.

        Before proceeding, we recommend checking the [list of open bug reports](https://github.com/ayoisaiah/focus/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) to confirm that your particular problem has not already been reported.

        If you do not find your issue listed, please proceed with your bug report. Your contribution is highly appreciated!

  - type: checkboxes
    id: issue-not-common
    attributes:
      label: Tick this box to confirm you have reviewed the above.
      options:
        - label: I've discovered a new issue with Focus.
          required: true

  - type: textarea
    id: focus-version
    attributes:
      label: What version of Focus are you using?
      description: Enter the output of `focus --version`. Please ensure you're using the [latest stable release](https://github.com/ayoisaiah/focus/releases/latest) before filing a bug report.
      placeholder: ex. focus v1.4.2
    validations:
      required: true

  - type: textarea
    id: install-method
    attributes:
      label: How did you install Focus?
      placeholder: ex. Go, Arch AUR, GitHub binary, NPM
    validations:
      required: false

  - type: textarea
    id: operating-system
    attributes:
      label: What operating system are you using Focus on?
      description: Enter your operating system name and version.
      placeholder: ex. Fedora 39, Windows 11
    validations:
      required: true

  - type: textarea
    id: focus-config
    attributes:
      label: What is your Focus configuration?
      description: |
        Run `focus edit-config` to view and copy your configuration, then paste it here

      value: |
        <!-- Example:
        work_mins: 50
        work_msg: Focus on your task
        short_break_mins: 10
        short_break_msg: Take a breather
        long_break_mins: 30
        long_break_msg: Take a long break
        long_break_interval: 4
        notify: true
        auto_start_work: false
        auto_start_break: true
        24hr_clock: false
        sound: ''
        sound_on_break: false
        work_sound: loud_bell
        break_sound: bell
        -->
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Describe your bug.
      description: Give a high level description of the bug.
      placeholder: ex. Focus fails to start a session when using the `--since` flag
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: What are the steps to reproduce the behavior?
      description: |
        Please describe the steps to trigger the bug. Be as detailed as possible so that Focus maintainers can reproduce it. Add screenshots if possible.
      placeholder: >
        ex. Run `focus --since '15 minutes ago'`
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: What behaviour did you observe?
      placeholder: |
        Recieved an unexpected error: Cannot parse '15 minutes ago' as time.Time
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: What is the expected behaviour?
      description: What do you think Focus should have done instead?
      placeholder: ex. The session should have started successfully with 35 minutes remaining
    validations:
      required: true
