name: Build darwin

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v3

      # Setup Go
      - name: Setup Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      # Tests
      - name: Build binary
        run: go build -o focus-darwin ./cmd/...

      - name: Archive darwin binary
        uses: actions/upload-artifact@v3
        with:
          name: focus-darwin
          path: focus-darwin

      - name: Download darwin binary
        uses: actions/download-artifact@v3
        with:
          name: focus-darwin
