name: Upload macOS binaries

env:
  dev_tag: nightly

on:
  workflow_run:
    workflows: [Release Focus]
    types:
      - completed

jobs:
  build_and_upload:
    runs-on: macos-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go v1.21
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Build assets with Goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean --snapshot --config=.goreleaser_darwin.yml

      - name: Upload archives to nightly release
        run: gh release upload ${{ env.dev_tag }} dist/*.tar.gz dist/darwin-checksums.txt --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

