name: golangci-lint
on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install libasound2-dev
        run: sudo apt install libasound2-dev

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
