name: Update issue labels

on:
  pull_request:
    branches:
      - master
    paths:
      - .github/labels.yml
      - .github/workflows/labeler.yml

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
