name: Publish to NPM

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Publish new Focus version
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
          node-version: '20'

      - name: Create publish directory
        run: mkdir npm-publish

      - name: Copy relevant files
        run: cp README.md CHANGELOG.md package.json npm-publish

      - name: Change directory
        run: cd npm-publish

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
