name: Tests

on:
  pull_request:
    branches:
      - master

jobs:
  run_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install libasound2-dev
        run: sudo apt install libasound2-dev
        if: matrix.os == 'ubuntu-latest'

      # Tests
      - name: Run tests
        run: go test ./... -race
