name: Tests

on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Windows git setup
      if: matrix.os == 'windows-latest'
      run: git config --global core.autocrlf false

    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Install libasound2-dev
      run: sudo apt install libasound2-dev
      if: matrix.os == 'ubuntu-latest'

    # Tests
    - name: Run testing
      run: go test ./... -race
